### ISSUE TITLE
Checkpoint

### ISSUE THREAD

**Issue by DanielMitiku** [YuWVandy/Large-Graph-Generative-Model#1]
Can you let me know where I can find the checkpoint for the trained model?

**Comment by DanielMitiku** [comment]
For anyone looking, you can find it here: https://huggingface.co/spaces/YuWang0103/LGGM-Text2Graph/tree/main

**Comment by yuwvandy** [comment]
> For anyone looking, you can find it here: https://huggingface.co/spaces/YuWang0103/LGGM-Text2Graph/tree/main

Thank you Daniel!
